### ISSUE TITLE
version 7.3.6 detected virus

### ISSUE THREAD

**Issue by JohnGithub917** [getlantern/lantern-forum-en#2]
@myleshorton can you have a look? thanks.

**Comment by jay-418** [comment]
Hi @JohnGithub917, sorry for the extended delay, but I wanted to share that it is not uncommon for new releases to be provisionally tagged by security software. This is only because the software is brand new, and is tagged as a precaution. To ensure the best circumvention capacity, we frequently make updates.

Lantern software does not pose any security threats, and you can always verify the hash of a download to ensure that the verified build that we provide has not been tampered with in transit.

- Downloads: https://github.com/getlantern
- Hashes: https://github.com/getlantern/lantern-binaries/
